#!/usr/bin/env python3
import sys
from os.path import isfile
from IPython import embed


if __name__ == "__main__":
    
    if len(sys.argv) == 2 :
        uipy3_filename = "." + sys.argv[1] + ".uipy3"
        if isfile(uipy3_filename):
            exec(open(uipy3_filename).read())
    else:
        uipy3_filename = ".default.uipy3"
        if isfile(uipy3_filename):
            exec(open(uipy3_filename).read())
        else:
            print ("creating "+ uipy3_filename)
            f = open(uipy3_filename,"w")
            f.close
    
    print ("uipy -> " + uipy3_filename)
    
    embed()
