#!/usr/bin/env python3
from sys import argv as _argv
from os.path import isfile
from os.path import exists
from os.path import expanduser
from os import listdir
from os import mkdir
from IPython import embed


if __name__ == "__main__":
    
    uipy_filename = ""
    
    if len(_argv) == 2 :
        
        if isfile(_argv[1]):
            uipy_filename = _argv[1]
        else:
            if "-h" == _argv[1] or "h" == _argv[1]:
                print ("-h this help\n-s select scrips\nfilename.uipy direct load this file")
                exit(0)
                
            if "-s" == _argv[1]:
                userdir = expanduser("~/")
                if not exists(userdir + "uipy/"):
                    mkdir(userdir + "uipy/")
                
                l = listdir(userdir + "uipy/")
                d = {}
                if len(l) != 0:
                    for i in range(len(l)):
                        d[i] = l[i]
                        print (i, l[i])

                    f = input("seleccione el archivo: ")
                    uipy_filename = userdir + "uipy/" + d[int(f)]
                
    if len(_argv) == 1:
        uipy_filename = ".default.py"
        if isfile(uipy_filename):
            filename = uipy_filename
        else:
            print ("creating "+ uipy_filename)
            f = open(uipy_filename,"w")
            f.close
            filename = uipy_filename
    
    if uipy_filename != "":
        print ("uipy -> " + uipy_filename)
        exec(open(uipy_filename).read())
        embed()
