#!/usr/bin/env python3
import sys
from os.path import isfile
from os.path import exists
from os import listdir
from os import system
from os.path import expanduser
from IPython import embed


if __name__ == "__main__":
    
    uipy3_filename = ""
    
    if len(sys.argv) == 2 :
        
        if isfile(sys.argv[1]):
            uipy3_filename = sys.argv[1]
        else:
            if "-h" == sys.argv[1] or "h" == sys.argv[1]:
                print ("-h this help\n-s select scrips\nfilename.uipy3 direct load this file")
                exit(0)
                
            if "-s" == sys.argv[1]:
                userdir = expanduser("~/")
                if not exists(userdir + "uipy3/"):
                    system("mkdir " + userdir + "uipy3")
                
                l = listdir(userdir + "uipy3/")
                d = {}
                print(l)
                for i in range(len(l)):
                    d[i] = l[i]
                
                print(d)
                f = input("seleccione el archivo: ")
                uipy3_filename = userdir + "uipy3/" + d[int(f)] 
                
    if len(sys.argv) == 1:
        uipy3_filename = ".default.uipy3"
        if isfile(uipy3_filename):
            filename = uipy3_filename
        else:
            print ("creating "+ uipy3_filename)
            f = open(uipy3_filename,"w")
            f.close
            filename = uipy3_filename
    
    if uipy3_filename != "":
        print ("uipy -> " + uipy3_filename)
        exec(open(uipy3_filename).read())
        embed()
